### ISSUE TITLE
current version fails to run with WIne 

### ISSUE THREAD

**Issue by JDJoe** [Xjph/ObservatoryCore#202]
Failed to load System.Private.CoreLib.dll 

Version 1.1.1 runs fine

**Comment by jmczab** [comment]
I can reproduce error above on 1.2.4 (3aa0b51) using a version 8 based WINE. 
The latest wine-staging 10.0rc3 fails differently, and just bails out to debugger.

However, it does work using Proton 9 (using umu-launcher) on a new portable install  - new prefix, adding dotnetcore8 or 9, and corefonts.

Creating a working config file (using Proton) and then switching back to wine-staging 10rc3 allows the client to work, but the settings panel breaks when clicked with an error related to same library as above.

I am sticking with Proton for now :)

**Comment by Xjph** [comment]
I'll have a new wine-friendlier build soon, but there are some compatibility issues with .NET 8 and commonly distributed versions of Wine which I unfortunately can't do anything about. The only solution is to use a version of Wine new enough to support it.

I'll ping anyone in this comment chain once I have a more compatible build and a specific version of wine that I can suggest.

**Comment by Xjph** [comment]
@JDJoe @jmczab A new experimental 1.2.5 build is now available that should behave better with Wine.

https://observatory.xjph.net/release/experimental

**Comment by jmczab** [comment]
Herald plugin displays an error on all these, but I don't use it.

Tested OK: Tested Journal reading, scrolling and entries,  exports, settings, popup notification overlay
- Steam Proton - Experimental
- Steam Proton 9
- GE's GE-Proton9-22
- Lutris's wine-ge-8-26

Crashes:
Steam Proton 9, Steam Proton - Experimental, GE's GE-Proton9-22: When you click the options arrow next to the plugin

**Comment by Xjph** [comment]
@jmczab Crashes when using Wine 9, and likely anything based on it, are unfortunately expected and no fix is planned. 

I don't have the specifics in front of me at the moment but there's a bug in Wine's implementation of dpi awareness for .NET 8 which causes an exception when some types of controls are shown, and unfortunately the menu control being used for that menu is one. The same crash likely happens when right-clicking a tab as well. This is fixed in Wine 10.

...that said, am I reading this correctly that wine-ge-8-26 is working? That surprises me, but is a good thing to know if so.

As for Herald, the API is uses is currently offline and it will not function in any environment, Wine or Windows. It ended up costing more than expected to provide the cloud-based voice synth and I had to pull the plug. It should return _at some point_, but I don't currently have an eta.

**Comment by jmczab** [comment]
@Xjph Yes, wine-ge-8-26 - (GloriousEggroll's last wine update) does work. Probably WINE 8 will as well. Not many distros have 10 yet - I get mine from WineHQ, but at least there are options.

I did tweak the DPI to be more readable on 4k, rechecked on defaults, but still crashes.

Fair enough - never used Herald, it still appears in the API list :) Thanks for confirming.

**Comment by Xjph** [comment]
As it happens Wine 10 was released to the stable channel just today. Hopefully that will mean it soon percolates out to the various easier-to-obtain packages for regular users.

**Comment by morphiak** [comment]
Working using wine friendly version with kron4ek-wine-10.1-amd64 runner in bottles on bazzite.
